### ISSUE TITLE
Changing selected Item from viewdidLoad

### ISSUE THREAD

**Issue by wilferrel** [KieranLafferty/KLHorizontalSelect#1]
How can I create the Navigation Bar object with a different Index being selected at run time. For example: Selecting Like instead of : Hot ..

**Comment by wilferrel** [comment]
Let me also add that I have already tried to modify this:
 //Initialize the selected index to the first position
        self.selectedIndex = [NSIndexPath indexPathForRow:0 inSection:0];

and call it:
self.objectName.selectedIndex = [NSIndexPath indexPathForRow:1 inSection:0];
and
self.objectName.selectedIndex = [NSIndexPath indexPathForRow:0 inSection:1];

**Comment by KieranLafferty** [comment]
Added example of this functionality to the project
