### ISSUE TITLE
Doesn't always select correct cell

### ISSUE THREAD

**Issue by H2OBorne** [KieranLafferty/KLHorizontalSelect#3]
I have noticed that if you try and end the scroll in between a cell, that this can lead to selecting an invalid cell and the scrolling gets a bit messed up - for example when you release the touch, the selector jumps a couple of cells.

Has anyone else noticed this? I haven't looked into the code very much yet...
![iOS Simulator Screen shot 17 12 2012 7 38 03 PM](https://f.cloud.github.com/assets/1198483/16186/8989710e-4814-11e2-960d-ab620e0ebfbb.png)

**Comment by KieranLafferty** [comment]
Fixed with most recent commit
