### ISSUE TITLE
Arrow alignment with smaller kDefaultCellHeight (ex:60)

### ISSUE THREAD

**Issue by hdacosta** [KieranLafferty/KLHorizontalSelect#5]
Hello,

when changing kDefaultCellHeight to a smaller value, arrow is not aligned with the middle of the cell, it goes too much on the right and top's image disappears under navigation controller (in my case)

Great component by the way, i love it already.

**Comment by KieranLafferty** [comment]
Hey sorry for the delay fix incoming
