### ISSUE TITLE
iOS 5 Compatibility

### ISSUE THREAD

**Issue by bassrock** [KieranLafferty/KLHorizontalSelect#7]
According to the CocoaPods page this control is now iOS 5 compatible. However i am running into the following error:

[self.tableView registerClass:[KLHorizontalSelectCell class] forCellReuseIdentifier:reuseIdentifier];

It seems this method is iOS 6 only and the application crashes when it reachers this point.

Any ideas?

**Comment by bassrock** [comment]
Actually seemed to have fixed it with the following:

Change:

```
 static NSString* reuseIdentifier = @"HorizontalCell";
 [self.tableView registerClass:[KLHorizontalSelectCell class] forCellReuseIdentifier:reuseIdentifier];
 KLHorizontalSelectCell* cell = (KLHorizontalSelectCell*)[self.tableView  dequeueReusableCellWithIdentifier:reuseIdentifier];
```

To:

```
 static NSString* reuseIdentifier = @"HorizontalCell";
 KLHorizontalSelectCell* cell = (KLHorizontalSelectCell*)[self.tableView  dequeueReusableCellWithIdentifier:reuseIdentifier];
if(cell == nil) {
    cell = [[KLHorizontalSelectCell alloc] init];
}
```

**Comment by erolando** [comment]
Works for me!

**Comment by KieranLafferty** [comment]
Thanks for the fix!
